# Generated by Django 4.2.11 on 2024-03-09 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=100)),
                ('CustomerUserId', models.CharField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('CustomerPhone', models.CharField(max_length=15)),
                ('Comments', models.TextField(blank=True, null=True)),
                ('GovtFees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ApplicationNo', models.CharField(max_length=100)),
                ('FeesChargedToCustomer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Tehsil', models.CharField(max_length=100)),
                ('Referral', models.CharField(max_length=100)),
                ('documentType', models.CharField(max_length=100)),
                ('dateUploaded', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=100)),
                ('CustomerUserId', models.CharField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('CustomerPhone', models.CharField(max_length=15)),
                ('Comments', models.TextField(blank=True, null=True)),
                ('GovtFees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ApplicationNo', models.CharField(max_length=100)),
                ('FeesChargedToCustomer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Tehsil', models.CharField(max_length=100)),
                ('Referral', models.CharField(max_length=100)),
                ('documentType', models.CharField(max_length=100)),
                ('dateUploaded', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_documents', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
