# Generated by Django 5.0.1 on 2024-03-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending')], max_length=20),
        ),
    ]
